### ISSUE TITLE
Invalid list ref; please refer to InfiniteLoader documentation => not there

### ISSUE THREAD

**Issue by edwardsilhol** [bvaughn/react-window-infinite-loader#11] opened 2019-05-07 00:10 UTC
Hello,

Thanks for building this awesome library.

I'm seeing the above warning in the console, but there is no reference to it anywhere in the doc...

Also, my implementation seems correct and everything seems to be working perfectly.

Could you tell me why this is appearing?

Best,

Edward

**Comment by bvaughn** [comment] 2019-05-08 00:26
I'll take a look if you provide a repro. Otherwise, I can't help. Sorry!

**Comment by bvaughn** [comment] 2019-05-08 00:26
(Closing this for now since it has no repro)

**Closed by bvaughn** 2019-05-08 00:26 UTC

**Comment by ahorrocks2** [comment] 2019-05-15 23:06
I am seeing the same error if you wouldn't mind taking a look - keeping in mind I am relatively inexperienced with refs :) 

```
import { FixedSizeList as List } from 'react-window';
import AutoSizer from 'react-virtualized-auto-sizer';
import InfiniteLoader from 'react-window-infinite-loader';

<InfiniteLoader
      isItemLoaded={isItemLoaded}
      loadMoreItems={loadMoreItems}
      itemCount={itemCount}
      threshold={15}
    >
      {({ onItemsRendered, ref }) => (
        <Table>
          <TableBody>
            <AutoSizer>
              {({ height, width }) => (
                <List
                  className="List"
                  height={height}
                  itemCount={itemCount}
                  itemSize={50}
                  width={width}
                  onItemsRendered={onItemsRendered}
                  ref={ref}
                >
                  {Item}
                </List>
              )}
            </AutoSizer>
          </TableBody>
        </Table>
      )}
    </InfiniteLoader>
```

**Comment by bvaughn** [comment] 2019-05-15 23:12
Try moving the `InfiniteLoader` inside of the `AutoSizer`

**Comment by ahorrocks2** [comment] 2019-05-16 15:24
that worked, thank you!

**Comment by edwardsilhol** [comment] 2019-05-28 08:43
@bvaughn never saw your initial answer, but yes this did solve the problem, thanks a lot!

**Comment by mvasin** [comment] 2019-05-30 21:13
After fighting this false hierarchy I again and again praise hooks in my head.

@bvaughn Do you have plans to overhaul the API in favour of hooks?

**Comment by roelzkie15** [comment] 2019-11-09 18:05
@bvaughn 

This issue still persists despite moving the `InfiniteLoader` inside `Autosizer`.

```
import AutoSizer from "react-virtualized-auto-sizer";
import { FixedSizeList as List } from 'react-window-reversed';
import InfiniteLoader from "react-window-infinite-loader";

 <AutoSizer>
    {({height, width}) => (
        <InfiniteLoader
            isItemLoaded={isItemLoaded}
            itemCount={itemCount}
            loadMoreItems={loadMoreItems}
        >
            {({onItemsRendered, ref}) => (
                <List
                    height={height} 
                    width={width} 
                    itemSize={itemSize} 
                    itemCount={itemCount}
                    onItemsRendered={onItemsRendered}
                    reversed={true}
                >
                        {row}
                </List>
            )}
            
        </InfiniteLoader>
    )}
</AutoSizer>
```

BTW I'm using `react-window-reversed@1.4.1`.

**Comment by bvaughn** [comment] 2019-11-09 18:12
You're not setting the `ref`

**Comment by Cridda** [comment] 2019-11-26 14:03
I'm trying to use `WindowScroller` in combination with `InfiniteLoader`, but also getting this error.

See https://codesandbox.io/s/busy-nash-se7oq where I reproduced the error. What would you suggest in this case? Thanks in advance!

**Comment by bvaughn** [comment] 2019-11-26 16:31
@Cridda I'd suggest reading my response to the person above who posted exactly the same thing :smile: You're also not setting the ref (passed by `InfiniteLoader`)

**Comment by Cridda** [comment] 2019-11-26 16:38
I understand if don't have time to help me, so then I just want to thank you for your awesome libraries! 

However if you could look at my sandbox, you'll see I'm also using `WindowScroller` by following this example https://codesandbox.io/s/vy620pkzzy?from-embed.

So, there basically already is a ref I'm setting except not the one provided by `InfiniteLoader`.

**Comment by Cridda** [comment] 2019-11-26 16:56
@bvaughn I solved it by using the innerRef aswell

**Comment by bvaughn** [comment] 2019-11-26 17:05
I did look at the Sandbox ;) That's how I saw that the ref coming from `InfiniteLoader` wasn't being used :) Glad you got it sorted out.
